package com.citysight.security.enums;


import lombok.AllArgsConstructor;
import lombok.Getter;

@Getter
@AllArgsConstructor
public enum EnvironmentApiKey {
    LOCAL("THISISAVERYLONGANDSOMETHINGSOMETHINGHARDSECRETSALTWHATEVERITISBLABLABLABLABLABLABLALOOKSGOODIGUESS"),
    LOCAL2("THISISAVERYLONGANDSOMETHINGSOMETHINGHARDSECRETSALTWHATEVERITISBLABLABLABLATHISISSECONDONEBLABLABLALOOKSGOODIGUESS"),
    PROD("THISISAVERYLONGANDSOMETHINGSOMETHINGHARDSECRETSALTWHATEVERITISBLABLABLABLABLABLABLALOOKSGOODIGUESS"),
    PROD2("THISISAVERYLONGANDSOMETHINGSOMETHINGHARDSECRETSALTWHATEVERITISBLABLABLABLATHISISSECONDONEBLABLABLALOOKSGOODIGUESS"),
    ;
    private String value;
}
